export const data = [
      {
        id: '11231231',
        status: 'active',
        startDate:'01/08/2021',
        endDate:'10/08/2021',
        startLocation:'Buenos Aires',
        endLocation:'Puerto Madryn',
        agency:'Sur Management',
        channel:'EMI',
        pilots:'2',
        serviceQuality:'-',
        maniobra:'-',
        externalServices:'-',
        boat:{
          name:'Black Pearl',
          flag:'Argentina',
          cs:'9v6599',
          imo:'9470911',
          loa:'183.17',
          breadth:'32.20',
          depth:'18.80',
          cf:'139',
          sdrf:'12,425',
          grt:'29130',
        },
        
      },
      {
        id: '22222',
        status: 'active',
        startDate:'01/08/2021',
        endDate:'10/08/2021',
        startLocation:'Buenos Aires',
        endLocation:'Puerto Madryn',
        agency:'Sur Management',
        channel:'EMI',
        pilots:'2',
        serviceQuality:'-',
        maniobra:'-',
        externalServices:'-',
        boat:{
          name:'Black Pearl',
          flag:'Argentina',
          cs:'9v6599',
          imo:'9470911',
          loa:'183.17',
          breadth:'32.20',
          depth:'18.80',
          cf:'139',
          sdrf:'12,425',
          grt:'29130',
        },
        
      },
      {
        id: '333',
        status: 'active',
        startDate:'01/08/2021',
        endDate:'10/08/2021',
        startLocation:'Buenos Aires',
        endLocation:'Puerto Madryn',
        agency:'Sur Management',
        channel:'EMI',
        pilots:'2',
        serviceQuality:'-',
        maniobra:'-',
        externalServices:'-',
        boat:{
          name:'Black Pearl',
          flag:'Argentina',
          cs:'9v6599',
          imo:'9470911',
          loa:'183.17',
          breadth:'32.20',
          depth:'18.80',
          cf:'139',
          sdrf:'12,425',
          grt:'29130',
        },
        
      },
    ];


